### ISSUE TITLE
Contradictions in the effect direction between deltaSVM and QBiC-Pred

### ISSUE THREAD

**Issue by tianwen0003** [ren-lab/deltaSVM#10]
Hi 
I'am using both deltaSVM and QBiC-Pred (http://qbic.genome.duke.edu/makeprediction) to predict the effect of genome variants on TF binding, but for these two method, I always get opposite result for same SNP and same TF.  some examples from different TF family are listed below:

- "SNP(hg19)(chr_pos_ref_alt)"    "TF"               "prediction result from QBiC-Pred"                                                      "deltaSVM results"
- "chr10_126278191_C_T"           "ETV5"           "unbound>bound (mean ETV5 bind allele T other than allele C)"        "Loss "
- "chr10_115406307_A_G"           "HOXA10"     "bound>unbound"                                                                                "Gain"
- "chr10_35057854_C_A"             "ATF3"            "bound>unbound"                                                                               "Gain"

I think there must some problem of that, so I am reporting this issue to both of your groups.  I would be very grateful for any reply.

**Comment by tianwen0003** [comment]
I think you made a mistake in the closed issue #7 , I have a confident prediction for the effect of rs571633444 on the ETS TF family. Allele A have the high confidence to destory the binding of FLI1, but in the output of deltaSVM, the "preferred_allele" is "Gain", as your interpretation of the mening, this means allele A have stronger TF binding.

- snp     tf      allele1_bind    allele2_bind    seq_binding     deltaSVM_score  preferred_allele
- chr11_69064742_G_A      FLI1    0.152061        -1.200670       Y       -13.716620      Gain

![image](https://user-images.githubusercontent.com/32695781/160310683-3a81420a-eaeb-4db9-9d1f-30869c7f6ef5.png)

**Comment by yjqiu** [comment]
@tianwen0003 Thanks for letting us know. We have confidence in our models in general with extensive evaluation as described in the publication. And we cannot comment on other tools since we are not familiar with them. 

One thing I want to emphasize is that all predictions are with limitations and users should always use them with caution. Experimental validation should always be the gold standard.

We would keep those examples in mind and may evaluate them in the future. But it is hard to see the truth without further experiments.
